name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "85e5c3f9bf8640c293da8d2ad28f4bc4" },
  { binding = "SHARE", id = "02e3cf85dcc4427cb0708e0a42cd81d1" }
]